---
name: Geoff Harcourt
title: Geoff Harcourt

description: |
  I'm a software engineer and fantasy baseball enthusiast.
  I'm the CTO at CommonLit where we build a literacy curriculum that we
  provide for free to teachers and students.

avatar: https://avatars3.githubusercontent.com/u/319471?v=3&s=460

theme: jekyll-theme-minimal
