---
name: Geoff Harcourt
title: Geoff Harcourt

description: |
  I'm the CTO at CommonLit. We build a literacy curriculum that we provide for
  free to teachers and students.

avatar: https://avatars3.githubusercontent.com/u/319471?v=3&s=460

theme: jekyll-theme-minimal
